name: tetris
description: Flame Forge2D (box2d) samples

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame_audio: ^1.3.2
  flame_lint: ^0.1.1
  equatable: ^2.0.3
  intl: ^0.17.0
  flame: ^1.5.0
  flame_svg: ^1.7.0
  sprintf: ^7.0.0
  rxdart: ^0.27.7  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any  


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/svg/
