name: tetris
description: Flame Forge2D (box2d) samples

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame_forge2d: ^0.12.4
  flame_audio: ^1.3.2
  flame_lint: ^0.1.1
  equatable: ^2.0.3
  event_bus: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any  


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
