name: yatrix
description: Yet Another Tetris Clone

publish_to: 'none'

version: 0.9.0+67

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame_audio: ^1.3.2
  flame_lint: ^0.1.1
  equatable: ^2.0.3
  intl: ^0.17.0
  flame: ^1.5.0
  flame_svg: ^1.7.0
  sprintf: ^7.0.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  shared_preferences: ^2.0.15
  flutter_markdown: ^0.6.13
  peerdart: ^0.5.0  
  flutter_webrtc: ^0.9.19
  bot_toast: ^4.0.3
  collection: ^1.16.0
  pubspec_parse: ^1.2.1
  share_plus: ^6.3.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mocktail:


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/audio/music_zapsplat_game_music_childrens_soft_warm_cuddly_calm_015.mp3
    - assets/audio/pha.mp3
    - assets/audio/zapsplat_sound_design_transition_whoosh_fast_airy_002_74584.mp3
    - assets/audio/zapsplat_fantasy_magic_chime_ping_wand_fairy_godmother_013_38299.mp3
    - assets/audio/zapsplat_sound_design_transition_whoosh_fast_airy_002_74584.mp3
    - pubspec.yaml
